version: '3.4'

services:
  automanager:
    image: ${DOCKER_REGISTRY-}automanager
    build:
      context: .
      dockerfile: AutoManager/Dockerfile
  mysqldb:
    image: mysql:latest
    restart: always
    ports:
      - "3308:3306"
    volumes:
      - ./store/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=automanager
      - MYSQL_USER=felipe
      - MYSQL_PASSWORD=password
  rediscache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
  

